## Localisation of input database
DBpath_seq: "/home/master_students/bin/microbiome16S_pipeline/data/ezbiocloud201805/DB_amp.fasta" # reference genomic sequence in .fasta file
DBpath_tax: "/home/master_students/bin/microbiome16S_pipeline/data/ezbiocloud201805/DB_amp_taxonomy.txt" # reference taxonomic of these sequence

## Output
tax_DB_path: "/data/databases/amplicon_based_metagenomics/16S/" # path where to write the output of the database processing pipeline. 
tax_DB_name: "EzBioCloud_version" # The desired name of processed pipeline. 

#trimming
forward_primer: CCTACGGGNGGCWGCAG # the forward PCR primer used to extract the amplicon
reverse_primer: GACTACHVGGGTATCTAATCC # the reverse PCR primer used to extract the amplicon
length_max: 500 # the max length of the amplicon

#Filtering
numbers_species: 4 # the max number of species names to be pasted together 
numbers_genus: 2 # the max number of genus names to be pasted together 
