#localisation of database
DBpath_seq: "/home/master_students/bin/microbiome16S_pipeline/data/ezbiocloud201805/EzBioCloud_V3V4.fasta"
DBpath_tax: "/home/master_students/bin/microbiome16S_pipeline/data/ezbiocloud201805/EzBioCloud_V3V4_taxonomy.txt"

#trimming
forward_primer: CCTACGGGNGGCWGCAG
reverse_primer: GACTACHVGGGTATCTAATCC
length_max: 500

#Filtering
numbers_species: 4
numbers_genus: 2
