#localisation of database
DBpath_seq: "/home/master_students/bin/microbiome16S_pipeline/data/ezbiocloud_201805/ezbiocloud_qiime-full.fasta"
DBpath_tax: "/home/master_students/bin/microbiome16S_pipeline/data/ezbiocloud_201805/ezbiocloud_qiime-full.txt"
Output_folder: "/home/master_students/bin/microbiome16S_pipeline/data/ezbiocloud_201805_201905"

#trimming
forward_primer: CCTACGGGNGGCWGCAG
reverse_primer: GACTACHVGGGTATCTAATCC
length_max: 500

