#mandatory, one of them or both
sra_samples: example_sra_samples.tsv
local_samples: Metadata.tsv

# Trimming
forward_primer: CCTACGGGNGGCWGCAG
reverse_primer: GACTACHVGGGTATCTAATCC
DADA2_F_reads_length_trim: 280
DADA2_R_reads_length_trim: 255

# Filtering
merged_min_length: 390
merged_max_length: 500
F_extected_error: 2
R_extected_error: 2

# Visualization
viz_replace_empty_tax: TRUE
grouping_column: PatientID
x_axis_column: Sample
sample_type: sample_source
ordination_distance: ["unifrac", "wunifrac", "jsd", "bray", "jaccard", "chao"]
ordination_shape_column : sample_source

# Rarefaction
rarefaction_value: [10000,20000,50000,100000,200000,300000]

# Qiime stats
filtration_column: sample_group
filtration_value: sample
collapse_level: [2,3,4,5,6,7]
tested_factor: ["patientID", "Gender", "BMI","daily_consump"]

