#mandatory, one of them or both
sra_samples: example_sra_samples.tsv
local_samples: Metadata.tsv

# Trimming
forward_primer: CCTACGGGNGGCWGCAG
reverse_primer: GACTACHVGGGTATCTAATCC
DADA2_F_reads_length_trim: 280
DADA2_R_reads_length_trim: 255

# Filtering
merged_min_length: 390
merged_max_length: 500
F_extected_error: 2
R_extected_error: 2

# Denoisier
denoiser: ["vsearch", "DADA2"]

# Database
tax_DB: ["ezbiocloud_charlotte_merged", "ezbiocloud_charlotte_no_merge", "ezbiocloud_marta", "ezbiocloud_valentin"]

# Rarefaction
rarefaction_value: [10000,20000,50000,100000,200000,300000]

# Phyloseq processing
filter_tax_rank: ["Kingdom"]
filter_lineage: ["Bacterium"]
meta_column: ["sample_group"]
column_value: ["sample"]
collapse_level: [2,3,4,5,6,7]
subset_formula: "sum(x > 3) > (0.2*length(x)), TRUE"
viz_replace_empty_tax: TRUE

# Visualization
grouping_column: PatientID
x_axis_column: Sample
sample_type: sample_source
ordination_distance: ["unifrac", "wunifrac", "jsd", "bray", "jaccard", "chao"]
ordination_method: ["DCA", "CCA", "RDA", "CAP", "DPCoA", "NMDS", "MDS", "PCoA"]
ordination_shape_column : sample_source

#Qiime2 stat analysis
ANCOM_factors: ["Subject_ID", "Test_day", "Condition_group"]
Gneiss_gradient_clustering: ["Gneiss_gradient_clustering"]
Gneiss_formula: Subject_ID + Test_day + Condition_group
