#mandatory, one of them or both
sra_samples: example_sra_samples.tsv
local_samples: Metadata.tsv

# Trimming
forward_primer: CCTACGGGNGGCWGCAG
reverse_primer: GACTACHVGGGTATCTAATCC
DADA2_F_reads_length_trim: 280
DADA2_R_reads_length_trim: 255

# Fitering
merged_min_length: 390
merged_max_length: 500

#filtering
deblur_p_trim_length: 390

# Visualization
viz_replace_empty_tax: TRUE
grouping_column: "PatientID"
x_axis_column: "Sample"
